### ISSUE TITLE
TD4 - swss not coming up with latest code

### ISSUE THREAD

**Issue by anilkpan** [sonic-net/sonic-swss#3259]
When I load the latest community master image to the z9432f platform, I see the following error. swss is not coming up

root@sonic:/var/log# show logging ERR
2024-08-14T20:41:56.959303+00:00 sonic kernel: [    6.011437] EDAC MC0: Giving out device to module pnd2_edac controller Pondicherry2: DEV pnd2/dnv (INTERRUPT)
2024-08-14T20:41:56.959303+00:00 sonic kernel: [    6.011437] EDAC MC0: Giving out device to module pnd2_edac controller Pondicherry2: DEV pnd2/dnv (INTERRUPT)
2024 Aug 14 20:43:14.772812 sonic ERR ntpd[3626]: statistics directory /var/log/ntpsec/ does not exist or is unwriteable, error No such file or directory
2024 Aug 14 20:44:03.762380 sonic ERR monit[8562]: Unix socket /var/run/monit.sock connection error -- No such file or directory
2024 Aug 14 20:44:22.932766 sonic ERR systemd[1]: Failed to start swss.service - switch state service.
2024 Aug 14 20:44:22.935793 sonic ERR featured: ['sudo', 'systemctl', 'start', 'swss.service'] - failed: return code - 1, output:#012None
2024 Aug 14 20:44:22.935939 sonic ERR featured: Feature 'swss.service' failed to be enabled and started
2024 Aug 14 20:45:03.763367 sonic ERR monit[10175]: Unix socket /var/run/monit.sock connection error -- No such file or directory
2024 Aug 14 20:46:03.763162 sonic ERR monit[10683]: Unix socket /var/run/monit.sock connection error -- No such file or directory
2024 Aug 14 20:46:38.967336 sonic ERR systemctl[12041]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
2024 Aug 14 20:47:05.642241 sonic ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.11/dist-packages/ax_interface/mib.py", line 42, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 322, in reinit_data#012    updater.reinit_data()#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 663, in reinit_data#012    self._update_entity_cache(name)#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 960, in _update_entity_cache#012    fan_position = int(fan_position)#012                   ^^^^^^^^^^^^^^^^^#012ValueError: invalid literal for int() with base 10: ''
2024 Aug 14 20:47:12.647078 sonic ERR snmp#snmp-subagent [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.11/dist-packages/ax_interface/mib.py", line 42, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 322, in reinit_data#012    updater.reinit_data()#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 663, in reinit_data#012    self._update_entity_cache(name)#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 960, in _update_entity_cache#012    fan_position = int(fan_position)#012                   ^^^^^^^^^^^^^^^^^#012ValueError: invalid literal for int() with base 10: ''
2024 Aug 14 20:47:57.836504 sonic ERR snmp#snmp-subagent message repeated 8 times: [ [ax_interface] ERROR: MIBUpdater.start() caught an unexpected exception during update_data()#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.11/dist-packages/ax_interface/mib.py", line 42, in start#012    self.reinit_data()#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 322, in reinit_data#012    updater.reinit_data()#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 663, in reinit_data#012    self._update_entity_cache(name)#012  File "/usr/local/lib/python3.11/dist-packages/sonic_ax_impl/mibs/ietf/rfc2737.py", line 960, in _update_entity_cache#012    fan_position = int(fan_position)#012                   ^^^^^^^^^^^^^^^^^#012ValueError: invalid literal for int() with base 10: ]
2024 Aug 14 20:48:10.490613 sonic ERR systemctl[15455]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
2024 Aug 14 20:49:41.606824 sonic ERR systemctl[18579]: Failed to start dhcp_relay.service: Unit dhcp_relay.service is masked.
root@sonic:/var/log#

**Comment by adyeung** [comment]
@jeff-yin pls have someone from DELL to take a look

**Comment by jeff-yin** [comment]
Can someone assign this to @arunlk-dell ? I don't seem to have privileges to assign issues.

**Comment by adyeung** [comment]
@jeff-yin probably only the repo maintainer can assign as a formality, Arun can still submit a code PR fix and link with this, the merge of the fix will imply closing of the issue

**Comment by prsunny** [comment]
@arunlk-dell is not listed in assignee list. I cannot assig. @jeff-yin , i'll assign this to you for now

**Comment by arunlk-dell** [comment]
With the private build from latest source swss and orchagent is getting started and running. But syncd is exiting now.
And few SAI_API_UNSPECIFIED error are seen in the bootup logs..

`
2024 Oct 23 00:23:14.659995 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:502 Invalid sai_api_t 536870912 passed to sai_api_query
2024 Oct 23 00:23:14.660241 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:502 Invalid sai_api_t 536870913 passed to sai_api_query
2024 Oct 23 00:23:14.660399 sonic ERR syncd#syncd: [none] SAI_API_UNSPECIFIED:sai_api_query:502 Invalid sai_api_t 536870914 passed to sai_api_query
`

'sonic-broadcom.bin' master build is failing for more than a month.
https://sonic-build.azurewebsites.net/ui/sonic/pipelines/138/builds?branchName=master
